### ISSUE TITLE
Setting the animation prop doesn't add the CSS class

### ISSUE THREAD

**Issue by labber** [atomicpages/pretty-checkbox-react#2] opened 2019-03-25 13:45 UTC
**Describe the bug**
Adding the prop `Animation="tada"` to the component doesn't add the class in the source.

**pretty checkbox react version**: 1.0.5

**To Reproduce**
1. Add prop `Animaton="tada"` to the component
2. Save and Load the page
3. Click on the checkbox to test animation
4. Check the source and notice there is no class for the animation

**Expected behavior**
The class p-tada to be in the source code.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 10.14.3
 - Browser: Chrome 
 - Version: 72.0.3626.121

**Comment by atomicpages** [comment] 2019-03-28 03:17
Looks like a larger regression that's affecting all animations! Not sure how this happened 🤔

**Comment by atomicpages** [comment] 2019-03-28 03:43
Fixed in 80729d56ff626c025b425951d29343e0bf2be5fb. Thanks for making PCR better! Unit tests also added to ensure this issue doesn't happen in the future 😉

**Closed by atomicpages** 2019-03-28 03:43 UTC
Labels: bug
